version: '3.7'

services:
  web:
    image: docflow/chat_app:latest
    build:
      context: ./
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on: 
      - postgres

  nginx:
    image: docflow/my_first_web_deploy_nginx:latest
    build:
      context: ./nginx
    volumes:
        - static_volume:/usr/src/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  
  postgres:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=otabek
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=delivery
      - POSTGRES_PORT=5432

      
volumes:
  static_volume:
  postgres_data: