# Generated by Django 3.0.5 on 2020-04-16 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_description', models.CharField(max_length=200)),
                ('group_type', models.CharField(max_length=200)),
                ('group_text', models.TextField()),
                ('group_date_message', models.DateTimeField(verbose_name='date send')),
            ],
        ),
        migrations.CreateModel(
            name='Smiles',
            fields=[
                ('smile_id', models.AutoField(primary_key=True, serialize=False)),
                ('smile_img', models.ImageField(upload_to='images/')),
                ('smile_date_message', models.DateTimeField(verbose_name='date send')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_description', models.CharField(max_length=200)),
                ('chat_type', models.CharField(max_length=200)),
                ('chat_text', models.TextField()),
                ('date_message', models.DateTimeField()),
                ('user_first_name_to', models.IntegerField(default='')),
                ('user_first_name_from', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
