# Generated by Django 2.2 on 2020-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_description', models.CharField(max_length=200)),
                ('chat_type', models.CharField(max_length=200)),
                ('chat_text', models.TextField()),
                ('date_message', models.DateTimeField(verbose_name='date send')),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_description', models.CharField(max_length=200)),
                ('group_type', models.CharField(max_length=200)),
                ('group_text', models.TextField()),
                ('group_date_message', models.DateTimeField(verbose_name='date send')),
            ],
        ),
        migrations.CreateModel(
            name='Smiles',
            fields=[
                ('smile_id', models.AutoField(primary_key=True, serialize=False)),
                ('smile_img', models.ImageField(upload_to='images/')),
                ('smile_date_message', models.DateTimeField(verbose_name='date send')),
            ],
        ),
    ]
