# Generated by Django 2.1.5 on 2020-06-06 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs_chat_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField()),
                ('user_long', models.DecimalField(decimal_places=9, max_digits=20)),
                ('user_lat', models.DecimalField(decimal_places=9, max_digits=20)),
                ('product_long', models.DecimalField(decimal_places=9, max_digits=20)),
                ('product_lat', models.DecimalField(decimal_places=9, max_digits=20)),
                ('driver_long', models.DecimalField(decimal_places=9, max_digits=20)),
                ('driver_lat', models.DecimalField(decimal_places=9, max_digits=20)),
                ('shipping_long', models.DecimalField(decimal_places=9, max_digits=20)),
                ('shipping_lat', models.DecimalField(decimal_places=9, max_digits=20)),
                ('date_create', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_name', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=255)),
                ('date_payed', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('payment_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Payment_data')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('age', models.CharField(max_length=50, null=True)),
                ('sex', models.CharField(max_length=50, null=True)),
                ('user_longitude', models.DecimalField(decimal_places=9, max_digits=20)),
                ('user_latitude', models.DecimalField(decimal_places=9, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=9, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.CharField(max_length=200)),
                ('type_name', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=200)),
                ('price_per_unit', models.DecimalField(decimal_places=9, max_digits=20)),
                ('in_stock', models.DecimalField(decimal_places=9, max_digits=20)),
                ('product_longitude', models.DecimalField(decimal_places=9, max_digits=20)),
                ('product_latitude', models.DecimalField(decimal_places=9, max_digits=20)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Product_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.IntegerField()),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField()),
                ('shipping_address', models.CharField(max_length=250)),
                ('billing_address', models.CharField(max_length=250)),
                ('product_type', models.DecimalField(decimal_places=9, max_digits=20)),
                ('delivery_cost', models.DecimalField(decimal_places=9, max_digits=20)),
                ('discount', models.DecimalField(decimal_places=9, max_digits=20)),
                ('final_price', models.DecimalField(decimal_places=9, max_digits=20)),
                ('shipment_longitude', models.DecimalField(decimal_places=9, max_digits=20)),
                ('shipment_latitude', models.DecimalField(decimal_places=9, max_digits=20)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Payment_type')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=9, max_digits=20)),
                ('price_per_unit', models.DecimalField(decimal_places=9, max_digits=20)),
                ('price', models.DecimalField(decimal_places=9, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_time', models.DateTimeField()),
                ('notes', models.TextField()),
                ('shipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status_catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='docs_chat_profile.Product')),
                ('in_stock', models.DecimalField(decimal_places=9, max_digits=20)),
                ('last_update', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='shipment_status',
            name='status_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Status_catalog'),
        ),
        migrations.AddField(
            model_name='shipment_details',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Product'),
        ),
        migrations.AddField(
            model_name='shipment_details',
            name='shipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Shipment'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Shipment_type'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Product_type'),
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Role'),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment_details',
            name='shipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Shipment'),
        ),
        migrations.AddField(
            model_name='payment_data',
            name='payment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Payment_type'),
        ),
        migrations.AddField(
            model_name='locations',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Product'),
        ),
        migrations.AddField(
            model_name='locations',
            name='shipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docs_chat_profile.Shipment'),
        ),
        migrations.AddField(
            model_name='locations',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
